### ISSUE TITLE
开放设置后台发送日志线程池最大数量的功能

### ISSUE THREAD

**Issue by freesnake** [qiniu/qiniu-logging-plugin#8]
避免因为海量日志情况下，因为日志发送较慢，影响网络负载。

**Comment by jemygraw** [comment]
fixed in 
026151b6f271b1ff2258743764e9a8a6aa282f37
465c498d5d0a6c4e139e650edf5248140acddd56
5de50cffe9344abbea1f7140404306749c21ed3f
a5811bb1cb5bb73bdcc833a1ff569a228f2ddb30
93ddf3da8af12e65f699aee73e84cdc31bda630a
